tasks:
  build-deps:
    runner: razorci/openjdk:11-buster
    steps:
    - checkout
    - commands:
      - |
      dotnet sonarscanner  
      /d:sonar.host.url="http://13.233.98.144:9000"  
      /d:sonar.login=${TOKEN}
      dotnet build
      dotnet sonarscanner end /d:sonar.login=${TOKEN}
